debug: false

mybatis:
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com:
      fly:
        dao: debug
server:
  port: 7777
spring:
  profiles:
    active: dev

