debug: false

dxy:
  datasource:
    main-data-source:
      url: jdbc:mysql://192.168.202.137:3306/push_message_source
      username: pangpeijie
      password: shagNuwiUs@utdeerUmrunwenosix7
    ds0:
      url: jdbc:mysql://192.168.202.137:3306/push_message_01
      username: pangpeijie
      password: shagNuwiUs@utdeerUmrunwenosix7
    ds1:
      url: jdbc:mysql://192.168.202.137:3306/push_message_02
      username: pangpeijie
      password: shagNuwiUs@utdeerUmrunwenosix7
    ds2:
      url: jdbc:mysql://192.168.202.137:3306/push_message_03
      username: pangpeijie
      password: shagNuwiUs@utdeerUmrunwenosix7
    ds3:
      url: jdbc:mysql://192.168.202.137:3306/push_message_04
      username: pangpeijie
      password: shagNuwiUs@utdeerUmrunwenosix7

#dxy:
#  datasource:
#    main-data-source:
#      url: jdbc:mysql://127.0.0.1:3306/push
#      username: root
#      password: 123456
#    ds0:
#      url: jdbc:mysql://127.0.0.1:3306/push_message_01
#      username: root
#      password: 123456
#    ds1:
#      url: jdbc:mysql://127.0.0.1:3306/push_message_02
#      username: root
#      password: 123456
#    ds2:
#      url: jdbc:mysql://127.0.0.1:3306/push_message_03
#      username: root
#      password: 123456
#    ds3:
#      url: jdbc:mysql://127.0.0.1:3306/push_message_04
#      username: root
#      password: 123456

mybatis:
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com:
      fly:
        dao: debug
server:
  port: 7777
